"""Curated OSINT resources directory.

This is static data only -- an OSINT-Framework-style library of reputable
sites/tools, organized by category. Nothing here ever makes a network call;
the server just hands the list to the browser as JSON and the browser
renders each entry as a plain `target="_blank"` link the user clicks
themselves. Keep entries well-known and reputable; a one-line `note` on
each explains what it's for or how it's used elsewhere in Recon.
"""

RESOURCES: dict[str, list[dict[str, str]]] = {
    "Meta / Frameworks": [
        {"name": "OSINT Framework", "url": "https://osintframework.com/",
         "note": "the original category-tree directory this section is modeled on"},
        {"name": "Awesome OSINT (GitHub)", "url": "https://github.com/jivoi/awesome-osint",
         "note": "large curated list of OSINT tools and resources"},
    ],
    "Usernames & People Search": [
        {"name": "WhatsMyName", "url": "https://whatsmyname.app/",
         "note": "checks a username across 500+ sites at once"},
        {"name": "Namechk", "url": "https://namechk.com/",
         "note": "username + domain availability sweep"},
        {"name": "Sherlock (GitHub)", "url": "https://github.com/sherlock-project/sherlock",
         "note": "self-hosted CLI username hunter across hundreds of sites"},
        {"name": "Pipl", "url": "https://pipl.com/",
         "note": "paid people-search aggregator, deep record linking"},
        {"name": "That'sThem", "url": "https://thatsthem.com/",
         "note": "free reverse people/address/phone lookup"},
        {"name": "FastPeopleSearch", "url": "https://www.fastpeoplesearch.com/",
         "note": "US public-records aggregator"},
        {"name": "TruePeopleSearch", "url": "https://www.truepeoplesearch.com/",
         "note": "US public-records aggregator, free"},
    ],
    "Email": [
        {"name": "Have I Been Pwned", "url": "https://haveibeenpwned.com/",
         "note": "breach exposure lookup by email/domain"},
        {"name": "Hunter.io", "url": "https://hunter.io/",
         "note": "finds and verifies corporate email addresses by domain"},
        {"name": "Epieos", "url": "https://epieos.com/",
         "note": "reverse email lookup to linked Google/social accounts"},
        {"name": "GHunt (GitHub)", "url": "https://github.com/mxrch/GHunt",
         "note": "Google-account OSINT from just an email address"},
        {"name": "MXToolbox", "url": "https://mxtoolbox.com/",
         "note": "MX/SPF/DMARC/blacklist checks for a domain"},
        {"name": "Mailscoop.io", "url": "https://mailscoop.io/",
         "note": "guesses corporate email address formats by domain"},
    ],
    "Phone": [
        {"name": "Sync.me", "url": "https://sync.me/",
         "note": "reverse phone lookup + caller ID"},
        {"name": "TrueCaller", "url": "https://www.truecaller.com/",
         "note": "crowd-sourced caller ID / spam lookup"},
        {"name": "FreeCarrierLookup", "url": "https://www.freecarrierlookup.com/",
         "note": "carrier + line type by number"},
        {"name": "NumLookupAPI", "url": "https://numlookupapi.com/",
         "note": "validation API -- Recon's own phone module can use this key"},
    ],
    "Domains & DNS": [
        {"name": "crt.sh", "url": "https://crt.sh/",
         "note": "certificate-transparency log search, finds subdomains -- Recon uses it directly"},
        {"name": "SecurityTrails", "url": "https://securitytrails.com/",
         "note": "historical DNS + WHOIS records"},
        {"name": "DNSDumpster", "url": "https://dnsdumpster.com/",
         "note": "free DNS recon + host-mapping visualizer"},
        {"name": "BuiltWith", "url": "https://builtwith.com/",
         "note": "technology-stack profiler for a site"},
        {"name": "who.is", "url": "https://who.is/",
         "note": "WHOIS + DNS lookup"},
        {"name": "ViewDNS.info", "url": "https://viewdns.info/",
         "note": "grab-bag of DNS/WHOIS/reverse-IP tools"},
    ],
    "IP & Network": [
        {"name": "Shodan", "url": "https://www.shodan.io/",
         "note": "internet-wide device/service search engine"},
        {"name": "Censys", "url": "https://search.censys.io/",
         "note": "internet-wide host/certificate search engine"},
        {"name": "InternetDB (Shodan)", "url": "https://internetdb.shodan.io/",
         "note": "free keyless ports/CVEs by IP -- Recon's domain/IP modules use this directly"},
        {"name": "AbuseIPDB", "url": "https://www.abuseipdb.com/",
         "note": "crowd-sourced abuse/spam reports by IP"},
        {"name": "ipinfo.io", "url": "https://ipinfo.io/",
         "note": "IP geolocation + ASN lookup"},
        {"name": "GreyNoise Visualizer", "url": "https://viz.greynoise.io/",
         "note": "classifies internet-wide scanner/mass-scan background noise"},
    ],
    "Breaches & Leaks": [
        {"name": "Have I Been Pwned", "url": "https://haveibeenpwned.com/",
         "note": "the standard breach-exposure checker"},
        {"name": "DeHashed", "url": "https://dehashed.com/",
         "note": "paid searchable breach-data index"},
        {"name": "XposedOrNot", "url": "https://xposedornot.com/",
         "note": "free breach-analytics API -- Recon's email module uses it directly"},
        {"name": "IntelligenceX", "url": "https://intelx.io/",
         "note": "search engine over leaks, darknet, and WHOIS history"},
    ],
    "Images & Reverse Image": [
        {"name": "Google Lens", "url": "https://lens.google.com/",
         "note": "reverse image search + object identification"},
        {"name": "TinEye", "url": "https://tineye.com/",
         "note": "reverse image search, strong on exact-match provenance"},
        {"name": "Yandex Images", "url": "https://yandex.com/images/",
         "note": "best-in-class for faces/people, less US-biased index"},
        {"name": "PimEyes", "url": "https://pimeyes.com/",
         "note": "paid face-search engine -- high-signal, use carefully"},
        {"name": "FotoForensics", "url": "https://fotoforensics.com/",
         "note": "error-level analysis for detecting image manipulation"},
        {"name": "Forensically", "url": "https://29a.ch/photo-forensics/",
         "note": "free image-forensics toolkit (ELA, clone detection, metadata)"},
    ],
    "Geolocation & Maps": [
        {"name": "Google Maps", "url": "https://www.google.com/maps",
         "note": "satellite/street imagery + geocoding"},
        {"name": "OpenStreetMap", "url": "https://www.openstreetmap.org/",
         "note": "free, community-editable map data"},
        {"name": "SunCalc", "url": "https://www.suncalc.org/",
         "note": "sun/shadow position for a place and time -- geolocation verification"},
        {"name": "Wikimapia", "url": "http://wikimapia.org/",
         "note": "user-annotated satellite map"},
        {"name": "Mapillary", "url": "https://www.mapillary.com/",
         "note": "crowd-sourced street-level imagery"},
        {"name": "NASA Worldview", "url": "https://worldview.earthdata.nasa.gov/",
         "note": "near-real-time satellite imagery"},
        {"name": "Flightradar24", "url": "https://www.flightradar24.com/",
         "note": "live + historical flight tracking"},
    ],
    "Social Media": [
        {"name": "X (Twitter) Advanced Search", "url": "https://twitter.com/search-advanced",
         "note": "native advanced search operators"},
        {"name": "Facebook Search", "url": "https://www.facebook.com/search/top/",
         "note": "native people/page/post search"},
        {"name": "LinkedIn People Search", "url": "https://www.linkedin.com/search/results/people/",
         "note": "professional-network people search"},
        {"name": "Reddit Search", "url": "https://www.reddit.com/search/",
         "note": "native post/comment search"},
        {"name": "TikTok", "url": "https://www.tiktok.com/",
         "note": "profile + hashtag browsing"},
        {"name": "Telegram Web", "url": "https://web.telegram.org/",
         "note": "public channel/group browsing"},
        {"name": "Mastodon instance directory", "url": "https://instances.social/",
         "note": "find/search Mastodon instances a handle might live on"},
    ],
    "Company & Business": [
        {"name": "OpenCorporates", "url": "https://opencorporates.com/",
         "note": "largest open database of company registration records"},
        {"name": "SEC EDGAR", "url": "https://www.sec.gov/edgar/search/",
         "note": "US public-company filings, full-text search"},
        {"name": "Crunchbase", "url": "https://www.crunchbase.com/",
         "note": "funding rounds, executives, company profiles"},
        {"name": "LinkedIn Company Search", "url": "https://www.linkedin.com/search/results/companies/",
         "note": "employee counts and org-structure signal"},
        {"name": "Glassdoor", "url": "https://www.glassdoor.com/",
         "note": "reviews, salaries, org-culture signal"},
        {"name": "Companies House (UK)", "url": "https://find-and-update.company-information.service.gov.uk/",
         "note": "UK company registry, free and official"},
    ],
    "Crypto & Blockchain": [
        {"name": "Blockchain.com Explorer", "url": "https://www.blockchain.com/explorer",
         "note": "BTC/ETH block explorer -- Recon's BTC module uses its API directly"},
        {"name": "Etherscan", "url": "https://etherscan.io/",
         "note": "the standard Ethereum block explorer"},
        {"name": "Blockchair", "url": "https://blockchair.com/",
         "note": "multi-chain block explorer + search"},
        {"name": "Arkham Intel Exchange", "url": "https://intel.arkm.com/",
         "note": "entity attribution for wallets and addresses"},
        {"name": "OXT", "url": "https://oxt.me/",
         "note": "Bitcoin transaction-graph explorer"},
        {"name": "Ethplorer", "url": "https://ethplorer.io/",
         "note": "ETH + token balances -- Recon's ETH module uses its API directly"},
    ],
    "Threat Intel": [
        {"name": "VirusTotal", "url": "https://www.virustotal.com/",
         "note": "multi-AV file/URL/IP/domain reputation"},
        {"name": "AlienVault OTX", "url": "https://otx.alienvault.com/",
         "note": "community threat-intel pulses -- Recon's domain/IP modules use its API directly"},
        {"name": "CIRCL hashlookup", "url": "https://hashlookup.circl.lu/",
         "note": "known-file hash database -- Recon's hash module uses it directly"},
        {"name": "abuse.ch (URLhaus / MalwareBazaar / ThreatFox)", "url": "https://abuse.ch/",
         "note": "malware and IOC feeds"},
        {"name": "urlscan.io", "url": "https://urlscan.io/",
         "note": "sandboxed page scans + screenshots -- Recon's domain module uses its API directly"},
        {"name": "MITRE ATT&CK", "url": "https://attack.mitre.org/",
         "note": "adversary tactics/techniques knowledge base"},
    ],
    "Archives": [
        {"name": "Wayback Machine", "url": "https://web.archive.org/",
         "note": "the standard web archive -- Recon's domain module uses its API directly"},
        {"name": "Archive.today", "url": "https://archive.ph/",
         "note": "on-demand page snapshots, resistant to takedowns"},
        {"name": "CachedView", "url": "https://cachedview.nl/",
         "note": "quick links into Google/Bing/Wayback caches"},
        {"name": "Common Crawl", "url": "https://commoncrawl.org/",
         "note": "petabyte-scale open web-crawl dataset"},
    ],
    "Metadata": [
        {"name": "ExifTool", "url": "https://exiftool.org/",
         "note": "the reference metadata-extraction tool, run locally"},
        {"name": "Jeffrey's EXIF Viewer", "url": "https://exif.regex.info/exif.cgi",
         "note": "browser-based EXIF viewer for a URL or upload"},
        {"name": "Metagoofil (GitHub)", "url": "https://github.com/opsdisk/metagoofil",
         "note": "harvests metadata from public documents on a domain"},
    ],
}
